name: bookapp
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.0-324.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  carousel_slider: ^4.2.1
  collection:
  shared_preferences: ^2.2.1
  appwrite: ^10.0.1
  provider: ^6.0.5
  flutter_native_splash: ^2.3.2
  extended_theme: ^0.2.0
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
